### PR TITLE
idk

### PR DESCRIPTION
**Pull request by wavebeem**
Still not sure how to make it work like `new Flow().then(a).then(b).else(c).then(d).else(e).run(value)`

### CODE REVIEW

**Comment by minamorl** [comment]
How is this way: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBIFt0B4AqA+ZAbwChlkwALCELAMTwAoYQAuZB4SdNnASmQC8BWrzYZs9ANylkEADYBnCHUbM2DaFAD2UNgFEo2qPyHIRYzCulkAriADuUOAAcGANzhybEHgBpk8HJyAEaIANYA-OqaOvqGOiYEfDzSAL7ExAhycAoKyACaEM64BMDoznIQ6NRgeeIlRDIIWiAKYFA2CGA6DM5QwB6QyFAQcAAmLXIAngF2XTpR7HBQAOZscCBTich8ROkylNQqTKzsnFU82+ZolvSNZGQjYDZQIMggEPYFRe6e3oIEZgMSjABQAOjsjhcvy8EF48OsyH2ZHkSmOAH01OwYrpkAYjFdRDcJAQSA9hhBnq9yBRQcgcsg7GEQFp7G8GYVilIZMjGQ4nK4PLC-MhMZ4QuFFhp4rj8QkATsiTh7g8ni83iDwTA5t0oBEwTDvPwIhFkELvDziPttSAusAWsg5FoViUOFxLjwVc1WlpKmCnSs3VVeIi1dTzug0hlvW0zX8UAJ3p9vsUQDZ0MFoIxeDIwYcQAwGAAPbZF5AAKmQAEYAAw5sh5qgFgP15CN6iFksKssAamQACZW+3m86h5CBQwAMwh6MtBS+iD+52GuGSIA

**Comment by wavebeem** [comment]
I tried to incorporate your feedback into a new approach! Try it out :D

**Comment by minamorl** [comment]
LGTM. Thanks for the great enhancement!
Can you add `export` to Workflow and related interfaces if there exist? And bring these test code to the outside pls. Then I'll merge it.

**Comment by minamorl** [comment]
If my understanding is correct, you are chaining Workflow to next one (both caused when passed or failed) defined in c'tor and loop it right?

**Review by minamorl — APPROVED** [review]

**Comment by wavebeem** [comment]
Take another look when you get time. I think there's still a small bug in a rare chance, so I added a `TODO` for testing that and fixing it later.

**Comment by minamorl** [comment]
OK. Thanks for PR! Will check that issue.

**Review by minamorl — APPROVED** [review]
LGTM

**Pull request merged**
